//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderFristDate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> delivered { get; set; }
        public Nullable<System.DateTime> deliveredDate { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> payId { get; set; }
        public Nullable<int> storeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> OrderEndDate { get; set; }
    }
}
