//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public Nullable<int> Price { get; set; }
        public int OrderID { get; set; }
        public int Service_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
