//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdutID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> status { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string Desription { get; set; }
        public string Detail { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public byte[] created_at { get; set; }
    }
}
