//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int CateID { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> ParentID { get; set; }
        public byte[] created_at { get; set; }
        public string Name { get; set; }
    }
}
