//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Service_ID { get; set; }
        public string ServiceName { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
    }
}
